(() => {
  /**
   * Lightweight glossary for the Robot Sales Assistant.
   *
   * Add new entries by appending to this array.
   * - `term`: Display term.
   * - `definition`: One-line plain-English definition.
   * - `aliases` (optional): Alternate spellings people may type.
   */
  const entries = [
    { term: '!important', definition: 'A CSS flag that makes a specific declaration win in the cascade (it overrides normal specificity/ordering rules).', aliases: ['important'] },
    { term: '.gitignore', definition: 'A Git config file that lists files/folders Git should not track in a repository.' },
    { term: '.htaccess', definition: 'An Apache configuration file (per-directory) used for rewrites, redirects, auth rules, and other server settings.' },
    { term: '.htpasswd', definition: 'A file used by Apache to store hashed usernames/passwords for HTTP Basic Authentication.' },
    { term: '.NET', definition: 'Microsoft\'s developer platform/runtime for building and running applications (C#, F#, VB.NET, etc.).', aliases: ['dotnet', 'dot net'] },
    { term: '.NET Framework', definition: 'The original Windows-focused .NET runtime (largely superseded by modern, cross‑platform .NET).', aliases: ['dotnet framework', 'net framework'] },
    { term: '/dev/null', definition: 'A Unix "null device" that discards anything written to it (often used to ignore output).', aliases: ['dev null'] },

    { term: '80/20 Rule', definition: 'The idea (Pareto principle) that ~80% of outcomes often come from ~20% of causes.', aliases: ['pareto principle', 'pareto rule'] },
    { term: '90/90 Rule', definition: 'A software adage: the first 90% of a project takes 90% of the time; the last 10% also takes 90%.' },
    { term: 'Percent-encoding', definition: 'A way to encode special characters in URLs using % followed by hex (e.g., space → %20).', aliases: ['percent encoding', 'url encoding'] },

    // HTTP status codes
    { term: '100', definition: 'HTTP 100 Continue — the server received headers and the client can continue sending the request body.', aliases: ['http 100'] },
    { term: '101', definition: 'HTTP 101 Switching Protocols — the server agreed to change protocols (e.g., upgrading to WebSocket).', aliases: ['http 101'] },
    { term: '102', definition: 'HTTP 102 Processing — indicates the server has accepted the request but has not completed it yet.', aliases: ['http 102'] },
    { term: '200', definition: 'HTTP 200 OK — the request succeeded.', aliases: ['http 200'] },
    { term: '201', definition: 'HTTP 201 Created — the request succeeded and a new resource was created.', aliases: ['http 201'] },
    { term: '202', definition: 'HTTP 202 Accepted — the request was accepted for processing but not completed yet.', aliases: ['http 202'] },
    { term: '204', definition: 'HTTP 204 No Content — the request succeeded but there is no body to return.', aliases: ['http 204'] },
    { term: '205', definition: 'HTTP 205 Reset Content — tells the client to reset the document view (rarely used on the modern web).', aliases: ['http 205'] },
    { term: '206', definition: 'HTTP 206 Partial Content — the server is returning only part of the resource (range requests).', aliases: ['http 206'] },
    { term: '207', definition: 'HTTP 207 Multi-Status — returns multiple status codes for WebDAV operations.', aliases: ['http 207'] },
    { term: '208', definition: 'HTTP 208 Already Reported — WebDAV response indicating members were already listed.', aliases: ['http 208'] },
    { term: '226', definition: 'HTTP 226 IM Used — indicates the response is a delta/patch (rare).', aliases: ['http 226'] },
    { term: '300', definition: 'HTTP 300 Multiple Choices — multiple possible representations are available.', aliases: ['http 300'] },
    { term: '301', definition: 'HTTP 301 Moved Permanently — a permanent redirect to a new URL.', aliases: ['http 301', 'redirect 301'] },
    { term: '302', definition: 'HTTP 302 Found — a temporary redirect (historically common).', aliases: ['http 302', 'redirect 302'] },
    { term: '303', definition: 'HTTP 303 See Other — redirect to another URL (often after a POST).', aliases: ['http 303'] },
    { term: '304', definition: 'HTTP 304 Not Modified — the cached version can be used (no response body).', aliases: ['http 304'] },
    { term: '305', definition: 'HTTP 305 Use Proxy — deprecated; instructed clients to use a proxy.', aliases: ['http 305'] },
    { term: '306', definition: 'HTTP 306 (Unused) — reserved and no longer used.', aliases: ['http 306'] },
    { term: '307', definition: 'HTTP 307 Temporary Redirect — temporary redirect that preserves the HTTP method.', aliases: ['http 307'] },
    { term: '308', definition: 'HTTP 308 Permanent Redirect — permanent redirect that preserves the HTTP method.', aliases: ['http 308'] },
    { term: '400', definition: 'HTTP 400 Bad Request — the server can\'t process the request due to client-side error.', aliases: ['http 400'] },
    { term: '401', definition: 'HTTP 401 Unauthorized — authentication is required or failed.', aliases: ['http 401'] },
    { term: '403', definition: 'HTTP 403 Forbidden — the server understood the request but refuses to authorize it.', aliases: ['http 403'] },
    { term: '404', definition: 'HTTP 404 Not Found — the requested resource doesn\'t exist at that URL.', aliases: ['http 404'] },
    { term: '405', definition: 'HTTP 405 Method Not Allowed — the HTTP method isn\'t supported for that endpoint.', aliases: ['http 405'] },
    { term: '406', definition: 'HTTP 406 Not Acceptable — the server can\'t return a response matching the client\'s Accept headers.', aliases: ['http 406'] },
    { term: '407', definition: 'HTTP 407 Proxy Authentication Required — auth is required to use the proxy.', aliases: ['http 407'] },
    { term: '408', definition: 'HTTP 408 Request Timeout — the server timed out waiting for the request.', aliases: ['http 408'] },
    { term: '409', definition: 'HTTP 409 Conflict — the request conflicts with the current state of the server resource.', aliases: ['http 409'] },
    { term: '410', definition: 'HTTP 410 Gone — the resource is permanently removed (and not coming back).', aliases: ['http 410'] },
    { term: '411', definition: 'HTTP 411 Length Required — the server requires a Content-Length header.', aliases: ['http 411'] },
    { term: '412', definition: 'HTTP 412 Precondition Failed — a conditional request failed (e.g., If-Match).', aliases: ['http 412'] },
    { term: '413', definition: 'HTTP 413 Payload Too Large — the request body is too large for the server to accept.', aliases: ['http 413'] },
    { term: '414', definition: 'HTTP 414 URI Too Long — the URL is too long for the server to handle.', aliases: ['http 414'] },
    { term: '415', definition: 'HTTP 415 Unsupported Media Type — the server doesn\'t support the request\'s Content-Type.', aliases: ['http 415'] },
    { term: '416', definition: 'HTTP 416 Range Not Satisfiable — the requested byte range can\'t be provided.', aliases: ['http 416'] },
    { term: '417', definition: 'HTTP 417 Expectation Failed — the server can\'t meet the requirements of the Expect header.', aliases: ['http 417'] },
    { term: '418', definition: 'HTTP 418 I\'m a teapot — a joke status code from an April Fools\' RFC.', aliases: ['http 418'] },
    { term: '421', definition: 'HTTP 421 Misdirected Request — the request was sent to a server that can\'t produce a response.', aliases: ['http 421'] },
    { term: '422', definition: 'HTTP 422 Unprocessable Content — the server understands the request but can\'t process it (often validation errors).', aliases: ['http 422', 'unprocessable entity'] },
    { term: '423', definition: 'HTTP 423 Locked — the resource is locked (WebDAV).', aliases: ['http 423'] },
    { term: '424', definition: 'HTTP 424 Failed Dependency — the request failed due to a dependent request failing (WebDAV).', aliases: ['http 424'] },
    { term: '425', definition: 'HTTP 425 Too Early — the server is unwilling to risk processing a request that might be replayed.', aliases: ['http 425'] },
    { term: '426', definition: 'HTTP 426 Upgrade Required — the client should switch protocols (e.g., to TLS).', aliases: ['http 426'] },
    { term: '428', definition: 'HTTP 428 Precondition Required — the request must be conditional to prevent lost updates.', aliases: ['http 428'] },
    { term: '429', definition: 'HTTP 429 Too Many Requests — you\'re being rate-limited.', aliases: ['http 429', 'rate limit'] },
    { term: '431', definition: 'HTTP 431 Request Header Fields Too Large — headers are too large.', aliases: ['http 431'] },
    { term: '451', definition: 'HTTP 451 Unavailable For Legal Reasons — access is blocked due to legal restrictions.', aliases: ['http 451'] },
    { term: '500', definition: 'HTTP 500 Internal Server Error — a generic server-side failure.', aliases: ['http 500'] },
    { term: '501', definition: 'HTTP 501 Not Implemented — the server doesn\'t support the requested functionality.', aliases: ['http 501'] },
    { term: '502', definition: 'HTTP 502 Bad Gateway — a proxy/gateway got an invalid response from an upstream server.', aliases: ['http 502'] },
    { term: '503', definition: 'HTTP 503 Service Unavailable — the server is overloaded or down for maintenance.', aliases: ['http 503'] },
    { term: '504', definition: 'HTTP 504 Gateway Timeout — a proxy/gateway timed out contacting an upstream server.', aliases: ['http 504'] },

    { term: '2FA', definition: 'Two-factor authentication — logging in using two independent factors (e.g., password + code).', aliases: ['two-factor authentication', 'mfa'] },
    { term: 'A/B testing', definition: 'A way to compare two versions (A and B) to see which performs better (clicks, signups, sales).', aliases: ['split test'] },
    { term: 'A11Y', definition: 'Shorthand for "accessibility" (A + 11 letters + Y).', aliases: ['a11y'] },

    { term: 'Absolute positioning', definition: 'CSS placement that removes an element from normal document flow and positions it relative to its nearest positioned ancestor.' },
    { term: 'Abstract syntax tree', definition: 'A tree representation of source code structure produced by a parser, used by compilers, linters, and bundlers.', aliases: ['ast'] },
    { term: 'Accessibility', definition: 'Building products so people with disabilities can use them effectively (keyboard, screen readers, contrast, etc.).' },
    { term: 'Affordance', definition: 'A design quality that signals how an element should be used — a button looks pressable, a link looks tappable.' },
    { term: 'Agile', definition: 'An iterative approach to building software with short cycles, feedback, and flexible planning.' },
    { term: 'AJAX', definition: 'A technique for updating parts of a web page without a full reload (via HTTP requests from JavaScript).', aliases: ['asynchronous javascript and xml'] },
    { term: 'AMP', definition: 'Accelerated Mobile Pages — a constrained page format intended for fast mobile rendering (less common today).', aliases: ['accelerated mobile pages'] },
    { term: 'Angular', definition: 'A full-featured framework for building large web apps (TypeScript-based).', aliases: ['angularjs'] },
    { term: 'Animation (CSS)', definition: 'Changes to CSS properties over time, defined with @keyframes and applied via the animation shorthand property.', aliases: ['css animation'] },
    { term: 'Apache HTTP Server', definition: 'A widely-used open-source web server, often paired with PHP and MySQL in LAMP stacks.', aliases: ['apache'] },
    { term: 'API', definition: 'Application Programming Interface — a defined way for software to communicate (often via HTTP).', aliases: ['application programming interface'] },
    { term: 'API gateway', definition: 'A front door for APIs that handles routing, auth, rate limits, and observability.' },
    { term: 'ARIA', definition: 'Accessible Rich Internet Applications — attributes/roles that help assistive tech understand UI components.', aliases: ['wai-aria', 'wAI-ARIA'] },
    { term: 'ARIA roles', definition: 'ARIA labels that describe what a UI element is (e.g., button, dialog) to assistive technologies.' },
    { term: 'ASCII', definition: 'A basic character encoding standard for English letters, numbers, and symbols.' },
    { term: 'Aspect ratio', definition: 'The proportional relationship between an element\'s width and height (e.g., 16:9 for widescreen).' },
    { term: 'Assertion', definition: 'A statement in a test that checks whether a condition is true, causing the test to fail if it isn\'t.', aliases: ['expect', 'assert'] },
    { term: 'Async/await', definition: 'JavaScript syntax that makes asynchronous code look synchronous by pausing execution at await until a Promise resolves.', aliases: ['async await'] },
    { term: 'At-rule', definition: 'A CSS instruction beginning with @ that defines behavior (e.g., @media, @keyframes, @import, @font-face).', aliases: ['css at-rule'] },
    { term: 'Atomic design', definition: 'A UI methodology by Brad Frost that builds interfaces from atoms → molecules → organisms → templates → pages.', aliases: ['atomic design methodology'] },
    { term: 'Attribute (HTML)', definition: 'Extra information added to an HTML tag that modifies its behavior or provides metadata (e.g., class, id, href, src).', aliases: ['html attribute'] },
    { term: 'Authentication', definition: 'Proving who you are (e.g., logging in with a password or passkey).', aliases: ['authn'] },
    { term: 'Authorization', definition: 'Determining what an authenticated user is allowed to do.', aliases: ['authz'] },
    { term: 'Auto-scaling', definition: 'Automatically adding or removing server instances in response to traffic load.' },
    { term: 'AVIF', definition: 'A modern image format that can be smaller than WebP/JPEG for photos (browser support varies).', aliases: ['av1 image file format'] },

    { term: 'Babel', definition: 'A toolchain that transforms modern JavaScript into versions compatible with older environments.' },
    { term: 'Backend', definition: 'Server-side code that handles data, business logic, APIs, and integrations.' },
    { term: 'Backlog', definition: 'An ordered list of features, bugs, and tasks waiting to be picked up by a development team.' },
    { term: 'Base64', definition: 'An encoding scheme that converts binary data to ASCII text — used for data URIs, email attachments, and JWTs.', aliases: ['base64 encoding', 'data uri'] },
    { term: 'Baseline (typography)', definition: 'The invisible line on which most letters sit in a typeface.' },
    { term: 'BDD', definition: 'Behavior-Driven Development — writing tests in plain language (Given/When/Then) that describe expected behavior.', aliases: ['behavior-driven development'] },
    { term: 'Bearer token', definition: 'A token that grants access to whoever "bears" it; it must be kept secret.' },
    { term: 'BEM', definition: 'Block Element Modifier — a CSS naming convention (.block__element--modifier) for predictable, component-based styles.', aliases: ['block element modifier'] },
    { term: 'Blend mode', definition: 'A CSS/graphics setting controlling how a layer blends with what\'s behind it (multiply, screen, overlay, etc.).', aliases: ['mix-blend-mode'] },
    { term: 'Blue-green deployment', definition: 'A release strategy maintaining two identical environments so you can switch traffic instantly with zero downtime.' },
    { term: 'Bootstrap', definition: 'A popular open-source CSS/JS framework for building responsive, mobile-first websites quickly.' },
    { term: 'Bounce rate', definition: 'The percentage of sessions where users leave without taking further action (definition varies by analytics tool).' },
    { term: 'Box model', definition: 'The CSS layout model where every element is a box with content, padding, border, and margin layers.', aliases: ['css box model'] },
    { term: 'Box shadow', definition: 'A CSS property that adds a shadow effect around an element\'s border box.', aliases: ['box-shadow'] },
    { term: 'Breakpoint', definition: 'A viewport width at which a CSS media query triggers a layout change for responsive design.' },
    { term: 'Brotli', definition: 'A modern compression algorithm that often compresses better than gzip for web text assets.' },
    { term: 'Bundler', definition: 'A tool (e.g., Webpack, Vite, Rollup) that combines JavaScript modules and assets into optimized output files.' },

    { term: 'Cache', definition: 'Stored data used to speed up future requests (e.g., browser cache, CDN cache, server cache).' },
    { term: 'Cache busting', definition: 'A technique to force clients to fetch a fresh file (often by changing the filename or adding a version hash).' },
    { term: 'Call stack', definition: 'The internal data structure that tracks which functions are currently executing and in what order.' },
    { term: 'Call to action', definition: 'A UI element (button/link/text) that asks the user to take a specific next step.', aliases: ['cta'] },
    { term: 'Callback', definition: 'A function passed as an argument to another function, to be called when an operation completes.' },
    { term: 'Canary deployment', definition: 'Gradually rolling a new release out to a small slice of users before promoting it to everyone.' },
    { term: 'Canonical link', definition: 'A page hint that indicates the preferred URL when multiple pages have similar/duplicate content.' },
    { term: 'CDN', definition: 'Content Delivery Network — a network of servers that cache and serve content closer to users.', aliases: ['content delivery network'] },
    { term: 'Certificate authority', definition: 'A trusted organization that issues digital certificates to verify website identities (e.g., Let\'s Encrypt).', aliases: ['ca', 'certificate authority'] },
    { term: 'Class (CSS)', definition: 'A reusable CSS selector prefixed with a dot (.classname) that can be applied to any HTML element.' },
    { term: 'Class (programming)', definition: 'A blueprint for creating objects that share properties and methods.' },
    { term: 'CLI', definition: 'Command-Line Interface — interacting with software via typed commands.', aliases: ['command-line interface'] },
    { term: 'CLI tool', definition: 'A program you run from the command line (often for build, deploy, or automation).' },
    { term: 'Clickjacking', definition: 'Tricking users into clicking something different than they think (often via hidden overlays/iframes).' },
    { term: 'Closure', definition: 'A function that retains access to variables from its outer scope even after that scope has finished executing.' },
    { term: 'CLS', definition: 'Cumulative Layout Shift — how much the layout unexpectedly moves while loading.', aliases: ['cumulative layout shift'] },
    { term: 'CMS', definition: 'Content Management System — software for creating, managing, and publishing digital content.', aliases: ['content management system'] },
    { term: 'Code review', definition: 'The process of examining another developer\'s code changes before they\'re merged, to catch bugs and improve quality.' },
    { term: 'Code splitting', definition: 'Breaking a JavaScript bundle into smaller chunks that load on demand rather than all at once.' },
    { term: 'Color contrast ratio', definition: 'A measure of the brightness difference between foreground and background colors, used to ensure text readability.' },
    { term: 'Compression', definition: 'Reducing file size to improve load time (e.g., gzip or Brotli).', aliases: ['compress'] },
    { term: 'Component', definition: 'A reusable, self-contained piece of UI with its own structure, styles, and logic.' },
    { term: 'Connection pool', definition: 'A cache of reusable database connections that avoids the overhead of opening a new connection for each query.' },
    { term: 'Container', definition: 'A lightweight, isolated runtime environment for an application and its dependencies.' },
    { term: 'Container query', definition: 'A CSS feature that applies styles based on the size of a containing element rather than the viewport.', aliases: ['@container'] },
    { term: 'Content', definition: 'The text, images, video, and other information on a page that communicates your message to users and search engines.', aliases: ['website content', 'page content', 'web content'] },
    { term: 'Content negotiation', definition: 'The process where a client and server agree on the format of the response (JSON vs XML, language, etc.).' },
    { term: 'Context API', definition: 'A React built-in for passing data through the component tree without manually threading props at every level.' },
    { term: 'Conversion rate', definition: 'The percentage of visitors who complete a desired action (e.g., signup, purchase, download).' },
    { term: 'Cookie', definition: 'A small piece of data stored by the browser and sent with requests (often used for sessions/tracking).', aliases: ['cookies'] },
    { term: 'Cookie banner', definition: 'A UI overlay that notifies users about cookie usage and collects consent, often required by GDPR and similar laws.' },
    { term: 'Core Web Vitals', definition: 'Google performance metrics focused on load speed, responsiveness, and visual stability (LCP, INP, CLS).', aliases: ['cwv'] },
    { term: 'CORS', definition: 'Cross-Origin Resource Sharing — rules that control which other origins can access your resources.' },
    { term: 'CQRS', definition: 'Command Query Responsibility Segregation — an architecture pattern that separates read and write operations into different models.', aliases: ['command query responsibility segregation'] },
    { term: 'Critical rendering path', definition: 'The sequence of steps (parse HTML → build DOM/CSSOM → layout → paint) the browser follows to display a page.' },
    { term: 'Cross-browser compatibility', definition: 'Ensuring a website works correctly across different browsers and browser versions.' },
    { term: 'CRUD', definition: 'Create, Read, Update, Delete — the basic operations for managing data.' },
    { term: 'CSP', definition: 'Content Security Policy — a security header that reduces XSS by restricting allowed content sources.' },
    { term: 'CSR', definition: 'Client-side rendering — the browser renders the app using JavaScript after initial load.', aliases: ['client-side rendering'] },
    { term: 'CSRF', definition: 'Cross-site request forgery — tricking a logged-in user\'s browser into making an unwanted request.' },
    { term: 'CSS', definition: 'Cascading Style Sheets — controls layout and styling for web pages.' },
    { term: 'CSS custom property', definition: 'A variable defined in CSS using --property-name syntax, reusable anywhere in the stylesheet.', aliases: ['css variable', 'custom property'] },
    { term: 'CSS Modules', definition: 'A build-time system that scopes CSS class names locally to a component so they don\'t leak globally.' },
    { term: 'CSS preprocessor', definition: 'A tool (SASS, LESS) that extends CSS with variables, nesting, mixins, and functions, compiling to plain CSS.', aliases: ['preprocessor'] },
    { term: 'CSS reset', definition: 'A stylesheet that strips browser default styles to provide a consistent cross-browser baseline.' },
    { term: 'CSS-in-JS', definition: 'A pattern where CSS styles are written in JavaScript files and scoped automatically to components.' },
    { term: 'CTR', definition: 'Click-through rate — percentage of people who click after seeing an ad/link/snippet.' },
    { term: 'Cypress', definition: 'A JavaScript end-to-end testing framework that runs tests directly in the browser.' },

    { term: 'Dark mode', definition: 'A color scheme using light text on a dark background, often toggled by the prefers-color-scheme media query.' },
    { term: 'Data attribute', definition: 'A custom HTML attribute (data-*) for storing extra data on elements without non-standard attributes.' },
    { term: 'Database', definition: 'A system for storing and querying structured data.', aliases: ['db'] },
    { term: 'Debounce', definition: 'Delaying a function call until after the user has stopped triggering it for a set period (e.g., search-as-you-type).' },
    { term: 'Declarative programming', definition: 'Describing what you want the program to accomplish without specifying step-by-step how to do it.' },
    { term: 'Defer (script)', definition: 'An HTML attribute that tells the browser to load a script after the HTML is parsed, avoiding render blocking.' },
    { term: 'Denormalization', definition: 'Adding redundant data to a database schema to speed up reads at the cost of write complexity.' },
    { term: 'Dependency', definition: 'An external package or library that your project relies on.' },
    { term: 'Dependency injection', definition: 'Providing a component\'s dependencies from outside (e.g., via constructor) rather than having it create them itself.' },
    { term: 'Deploy', definition: 'Releasing code or an application to a server environment (staging or production).' },
    { term: 'Deprecation', definition: 'Marking a feature as outdated and scheduled for removal, signaling developers to migrate to a newer alternative.' },
    { term: 'Design system', definition: 'A collection of reusable components, patterns, tokens, and guidelines that ensure consistent product UI.' },
    { term: 'Design token', definition: 'A named value (color, spacing, font size) that stores a design decision in a format usable across platforms.' },
    { term: 'Destructuring', definition: 'JavaScript syntax for unpacking values from arrays or properties from objects into named variables.' },
    { term: 'DevOps', definition: 'A culture and practice combining development and operations teams to ship software faster and more reliably.' },
    { term: 'DNS', definition: 'Domain Name System — translates domain names (example.com) into IP addresses.' },
    { term: 'Docker', definition: 'A tool for packaging apps into containers so they run consistently across environments.' },
    { term: 'DoS', definition: 'Denial of Service — making a service unavailable by overwhelming it or exploiting weaknesses.' },
    { term: 'DOM', definition: 'Document Object Model — the in-memory tree representation of an HTML document that JS can manipulate.' },
    { term: 'Domain', definition: 'A human-readable address for a website or service (e.g., example.com).', aliases: ['domain name'] },
    { term: 'DRY principle', definition: 'Don\'t Repeat Yourself — reducing repetition by abstracting shared logic into reusable functions or components.', aliases: ['dry', 'dont repeat yourself'] },
    { term: 'Dynamic import', definition: 'A JavaScript feature (import()) that loads a module on demand at runtime rather than at startup.' },

    { term: 'Edge computing', definition: 'Running code and caching data at servers geographically close to users, reducing latency.' },
    { term: 'Encryption', definition: 'Encoding data so only authorized parties with the correct key can read it.' },
    { term: 'End-to-end testing', definition: 'Testing a complete user flow across the full system (UI → backend → database) like a real user.', aliases: ['e2e testing'] },
    { term: 'Environment variable', definition: 'A named value set outside the application (in the OS or platform) for configuration — e.g., API keys, database URLs.', aliases: ['env var'] },
    { term: 'Error boundary', definition: 'A React component that catches JavaScript errors thrown by child components and displays a fallback UI.' },
    { term: 'esbuild', definition: 'An extremely fast JavaScript and TypeScript bundler/minifier written in Go.' },
    { term: 'ESLint', definition: 'A JavaScript/TypeScript linter that finds problems and enforces code style rules.' },
    { term: 'ESM', definition: 'ECMAScript Modules — the modern standard module system for JavaScript (import/export).', aliases: ['es modules'] },
    { term: 'Event', definition: 'An action or occurrence (click, keypress, resize, fetch) that code can listen and respond to.' },
    { term: 'Event delegation', definition: 'Attaching a single event listener to a parent element to handle events from many child elements efficiently.' },
    { term: 'Event listener', definition: 'A function registered via addEventListener() that fires when a specific event occurs on an element.' },
    { term: 'Event loop', definition: 'JavaScript\'s concurrency mechanism that picks tasks off a queue and runs them one at a time on the single thread.' },
    { term: 'Event sourcing', definition: 'An architecture pattern where state is derived from an immutable log of past events rather than stored directly.' },

    { term: 'FaaS', definition: 'Function as a Service — running code in short-lived functions without managing servers.', aliases: ['serverless functions'] },
    { term: 'Favicon', definition: 'The small icon associated with a website (shown in tabs, bookmarks, and shortcuts).', aliases: ['favorite icon', 'shortcut icon'] },
    { term: 'Feature flag', definition: 'A toggle in code that enables or disables a feature without requiring a new deployment.', aliases: ['feature toggle'] },
    { term: 'Figma', definition: 'A browser-based design and prototyping tool widely used for UI/UX design and collaboration.' },
    { term: 'Filter (CSS)', definition: 'A CSS property applying graphical effects (blur, brightness, contrast, grayscale) to an element.' },
    { term: 'First Contentful Paint', definition: 'The moment the browser renders the first piece of DOM content (text or image) on screen.', aliases: ['fcp'] },
    { term: 'First-party cookie', definition: 'A cookie set by the domain the user is currently visiting, typically used for sessions and preferences.' },
    { term: 'Flat design', definition: 'A UI style using clean shapes, solid colors, and minimal depth — no skeuomorphic textures or gradients.' },
    { term: 'Flexbox', definition: 'A CSS layout system for arranging items in one dimension (row or column).', aliases: ['flex'] },
    { term: 'Focus state', definition: 'The visual indicator (often an outline or ring) showing which element is currently focused via keyboard.' },
    { term: 'Font stack', definition: 'An ordered list of font families in CSS, used as fallbacks when earlier fonts aren\'t available.' },
    { term: 'Font weight', definition: 'The thickness of font strokes, specified numerically (100–900) or by keywords like bold or light.' },
    { term: 'Foreign key', definition: 'A column that references another table\'s primary key to link related records.' },
    { term: 'Form validation', definition: 'Checking user input for correctness before processing — can be client-side, server-side, or both.' },
    { term: 'Framework', definition: 'A structured foundation of code that provides conventions and built-in tools for building applications.' },
    { term: 'Frontend', definition: 'The part of an app the user interacts with (UI in the browser or client).' },
    { term: 'Full stack', definition: 'Working across frontend and backend (and often databases/infrastructure too).', aliases: ['full-stack'] },
    { term: 'Functional programming', definition: 'A programming paradigm treating computation as evaluating functions, avoiding shared mutable state.' },

    { term: 'Git', definition: 'A distributed version control system for tracking changes to code over time.' },
    { term: 'GitHub', definition: 'A platform for hosting Git repositories and collaborating on code.' },
    { term: 'Glassmorphism', definition: 'A UI trend using frosted-glass aesthetics — blurred, translucent backgrounds with subtle borders.' },
    { term: 'Google Fonts', definition: 'A free library of web fonts hosted by Google, embeddable with a <link> tag.' },
    { term: 'Graceful degradation', definition: 'Designing so the app still functions (with fewer features) when something fails or is unsupported.' },
    { term: 'Gradient (CSS)', definition: 'A smooth transition between colors in CSS, created with linear-gradient(), radial-gradient(), or conic-gradient().' },
    { term: 'GraphQL', definition: 'An API query language where clients request exactly the data they need, typically from a single endpoint.' },
    { term: 'Grid', definition: 'A CSS layout system for arranging items in two dimensions (rows and columns).', aliases: ['css grid'] },
    { term: 'gRPC', definition: 'A high-performance RPC framework using Protocol Buffers, commonly used for internal microservice communication.', aliases: ['grpc'] },
    { term: 'Gzip', definition: 'A compression format widely used to compress text assets like HTML/CSS/JS over HTTP.' },

    { term: 'Hash function', definition: 'An algorithm mapping data to a fixed-size output string — used for checksums, password storage, and caching.' },
    { term: 'Headless browser', definition: 'A web browser without a visible UI, used for automated testing, scraping, and screenshots.' },
    { term: 'Headless CMS', definition: 'A CMS that stores and manages content but delivers it via API rather than rendering HTML pages itself.' },
    { term: 'Higher-order function', definition: 'A function that takes other functions as arguments or returns a function as its result (e.g., map, filter, reduce).' },
    { term: 'Hook (React)', definition: 'A React function (useState, useEffect, etc.) that lets functional components use state and other React features.' },
    { term: 'Hot module replacement', definition: 'A dev-server feature that swaps changed modules in the running app without a full page reload.', aliases: ['hmr'] },
    { term: 'HTML', definition: 'HyperText Markup Language — structures content on web pages.', aliases: ['hypertext markup language'] },
    { term: 'HTML5', definition: 'The fifth major revision of HTML, adding semantic elements, audio/video, canvas, local storage, and new form APIs.' },
    { term: 'HTTP', definition: 'Hypertext Transfer Protocol — the core protocol for web requests/responses.', aliases: ['hypertext transfer protocol'] },
    { term: 'HTTP/2', definition: 'A major revision of HTTP using multiplexing, header compression, and server push for improved performance.' },
    { term: 'HTTP/3', definition: 'The latest version of HTTP built on the QUIC transport protocol, offering faster connections and better packet-loss recovery.' },
    { term: 'HTTPS', definition: 'HTTP over TLS — encrypted HTTP that protects privacy and integrity on the web.' },
    { term: 'HSTS', definition: 'HTTP Strict Transport Security — tells browsers to use HTTPS only for a site for a period of time.' },
    { term: 'Husky', definition: 'A tool for running scripts (like linting) automatically on Git hooks (pre-commit, pre-push).' },
    { term: 'Hydration', definition: 'Attaching JavaScript event handlers to server-rendered HTML on the client to make it interactive.' },

    { term: 'IaaS', definition: 'Infrastructure as a Service — the cloud provider supplies VMs and networking; you manage the OS and up.', aliases: ['infrastructure as a service'] },
    { term: 'Idempotent', definition: 'A request is idempotent if calling it multiple times produces the same result as calling it once (GET and PUT are idempotent; POST is not).' },
    { term: 'Immutability', definition: 'The principle of never modifying existing data — instead creating new copies with the changes applied.' },
    { term: 'Imperative programming', definition: 'Writing code that describes step-by-step how to accomplish a task (as opposed to declarative style).' },
    { term: 'Infinite scroll', definition: 'A UI pattern that automatically loads and appends more content as the user scrolls toward the bottom.' },
    { term: 'Information architecture', definition: 'Organizing and labeling content so users can navigate and understand a website or app easily.' },
    { term: 'Infrastructure as code', definition: 'Managing servers and infrastructure through version-controlled config files rather than manual setup (e.g., Terraform).', aliases: ['iac'] },
    { term: 'Inline element', definition: 'An HTML element that flows with surrounding text rather than starting a new block (e.g., <span>, <a>, <strong>).' },
    { term: 'INP', definition: 'Interaction to Next Paint — how responsive a page feels during user interactions.', aliases: ['interaction to next paint'] },
    { term: 'Integration test', definition: 'A test that verifies multiple units, components, or services work together correctly.' },
    { term: 'Intersection Observer', definition: 'A browser API that efficiently detects when elements enter or leave the viewport — used for lazy loading and animations.' },
    { term: 'Islands architecture', definition: 'A web architecture where most of a page is static HTML and only interactive "islands" are hydrated as JavaScript components.' },

    { term: 'JAMstack', definition: 'An architecture approach based on JavaScript, APIs, and prebuilt Markup — separating the frontend from the backend.', aliases: ['jamstack'] },
    { term: 'JavaScript', definition: 'The programming language that runs in the browser to add interactivity and logic to web pages.' },
    { term: 'Jest', definition: 'A popular JavaScript testing framework from Meta, known for its zero-config setup and snapshot testing.' },
    { term: 'JSON', definition: 'JavaScript Object Notation — a common text format for APIs and configuration.' },
    { term: 'JSON-LD', definition: 'A method of encoding structured data in JSON within a <script> tag — used for SEO rich results and schema.org markup.', aliases: ['json linked data'] },
    { term: 'JWT', definition: 'JSON Web Token — a compact signed token often used for authentication/authorization.' },

    { term: 'Kanban', definition: 'A workflow method that visualizes work and limits in-progress tasks to improve flow.' },
    { term: 'Kerning', definition: 'Adjusting the spacing between specific pairs of characters in typography to improve visual balance.' },
    { term: 'Keyframe (CSS)', definition: 'A point in a CSS animation defined with @keyframes that specifies styles at a particular moment in time.' },
    { term: 'KISS principle', definition: 'Keep It Simple, Stupid — prefer simple, clear solutions over clever or complex ones.', aliases: ['kiss'] },
    { term: 'Kubernetes', definition: 'A system for running and scaling containers across clusters of machines.', aliases: ['k8s'] },

    { term: 'Lambda function', definition: 'A serverless function (AWS Lambda, etc.) that runs in response to events without managing servers; also an anonymous function in some languages.' },
    { term: 'Lazy loading', definition: 'Loading images/iframes/code only when they\'re close to being needed, to improve initial load speed.', aliases: ['lazyload', 'lazy-loading'] },
    { term: 'LCP', definition: 'Largest Contentful Paint — how fast the main content appears.', aliases: ['largest contentful paint'] },
    { term: 'Leading (typography)', definition: 'The vertical spacing between lines of text — called line-height in CSS.' },
    { term: 'Level AA', definition: 'A common WCAG conformance target (more strict than A, less strict than AAA).', aliases: ['wcag aa', 'aa'] },
    { term: 'Level AAA', definition: 'The strictest WCAG conformance level (often difficult to meet for all content).', aliases: ['wcag aaa', 'aaa'] },
    { term: 'Library', definition: 'A collection of pre-written code your app calls to perform specific tasks — unlike a framework, it doesn\'t dictate structure.' },
    { term: 'Lighthouse', definition: 'An open-source, automated Google tool for auditing web page performance, accessibility, SEO, and best practices.' },
    { term: 'Linting', definition: 'Automatically checking code for mistakes and style issues (often via a linter).', aliases: ['linter'] },
    { term: 'Load balancer', definition: 'A system that distributes traffic across multiple servers to improve reliability and capacity.' },
    { term: 'Local storage', definition: 'Browser storage for key/value data that persists until cleared (per origin).', aliases: ['localStorage'] },
    { term: 'Logging', definition: 'Recording events/requests/errors so you can debug issues and monitor behavior.' },

    { term: 'Markup', definition: 'HTML tags and structure added to content to define its meaning and presentation in a browser.' },
    { term: 'Media query', definition: 'A CSS feature that applies styles based on device characteristics (width, prefers-color-scheme, etc.).' },
    { term: 'Memoization', definition: 'Caching a function\'s return value for given inputs so it doesn\'t recompute on repeated calls with the same arguments.' },
    { term: 'Meta tag', definition: 'HTML elements in <head> providing metadata — description, viewport, charset, Open Graph tags, and more.' },
    { term: 'Microservices', definition: 'An architecture where an application is split into small, independently deployable services.' },
    { term: 'Middleware', definition: 'A function or layer that sits between two systems and processes requests/responses as they pass through.' },
    { term: 'Migration (database)', definition: 'A versioned script that applies incremental changes to a database schema in a controlled, repeatable way.' },
    { term: 'Mock', definition: 'A fake implementation of a dependency used in tests to isolate the code under test.' },
    { term: 'Modal', definition: 'A dialog overlay that appears on top of the page and requires user interaction before they can return to the main content.' },
    { term: 'Monitoring', definition: 'Watching systems for availability/performance issues (alerts, dashboards, health checks).' },
    { term: 'Monolith', definition: 'A single-deployment application where all functionality is bundled together in one codebase.' },
    { term: 'Monorepo', definition: 'A single repository containing multiple related packages or projects (e.g., managed with Turborepo or Nx).' },
    { term: 'Monospace font', definition: 'A typeface where every character occupies the same horizontal width — common in code editors.', aliases: ['monospace', 'fixed-width font'] },
    { term: 'MPA', definition: 'Multi-page application — a traditional website where navigation loads new HTML pages from the server.', aliases: ['multi-page application'] },
    { term: 'mTLS', definition: 'Mutual TLS — both client and server present certificates to authenticate each other.' },
    { term: 'MVC', definition: 'Model-View-Controller — an architectural pattern separating data (Model), UI (View), and logic (Controller).', aliases: ['model view controller'] },
    { term: 'MVP', definition: 'Minimum viable product — the smallest version you can ship to validate value and learn.' },

    { term: 'Namespace', definition: 'A container for identifiers that avoids naming conflicts between different code modules or libraries.' },
    { term: 'Native app', definition: 'An application built specifically for one platform (iOS, Android, macOS) using platform-native tools.' },
    { term: 'Neumorphism', definition: 'A UI style creating soft, extruded shapes using dual highlights and shadows on a same-color background.', aliases: ['soft ui'] },
    { term: 'Next.js', definition: 'A React framework supporting SSR/SSG, file-based routing, and production-ready web features.' },
    { term: 'Nginx', definition: 'A high-performance web server and reverse proxy widely used for static files, load balancing, and SSL termination.', aliases: ['nginx'] },
    { term: 'Node.js', definition: 'A JavaScript runtime for running JS on the server (outside the browser).' },
    { term: 'Normalize.css', definition: 'A CSS library that makes browser default styles consistent across browsers without removing all defaults.' },
    { term: 'NoSQL', definition: 'Databases that are not strictly relational (e.g., document, key-value, wide-column, graph).', aliases: ['non-relational database'] },
    { term: 'npm', definition: 'Node Package Manager — a tool for installing JavaScript packages and running scripts.', aliases: ['node package manager'] },
    { term: 'Nullish coalescing', definition: 'The ?? operator in JavaScript, returning the right-hand value only when the left is null or undefined.', aliases: ['??'] },

    { term: 'Object-oriented programming', definition: 'A programming paradigm organizing code as objects that combine data (properties) and behavior (methods).', aliases: ['oop'] },
    { term: 'OAuth', definition: 'An authorization framework that lets apps get limited access to a user\'s account without sharing passwords.' },
    { term: 'Open Graph', definition: 'Meta tags (og:title, og:image, etc.) that control how a URL is displayed when shared on social media.', aliases: ['opengraph', 'og tags'] },
    { term: 'Open source', definition: 'Software with publicly available source code that anyone can inspect, use, modify, and distribute.' },
    { term: 'OpenAPI', definition: 'A specification (formerly Swagger) for describing REST APIs in a machine-readable YAML/JSON format.', aliases: ['swagger', 'openapi specification'] },
    { term: 'OpenID Connect', definition: 'An identity layer on top of OAuth 2.0 used for login (authentication).', aliases: ['oidc'] },
    { term: 'ORM', definition: 'Object-relational mapper — a library that maps database rows to programming language objects, letting you query with code instead of raw SQL.', aliases: ['object relational mapper'] },
    { term: 'OWASP', definition: 'A nonprofit known for web security guidance, including the OWASP Top 10.', aliases: ['open web application security project'] },
    { term: 'OWASP Top 10', definition: 'A list of the most critical web application security risk categories (used for awareness and training).', aliases: ['top 10'] },

    { term: 'PaaS', definition: 'Platform as a Service — the cloud provider manages the runtime and infrastructure; you deploy apps.', aliases: ['platform as a service'] },
    { term: 'Package manager', definition: 'A tool (npm, yarn, pnpm) for installing, updating, and managing project software dependencies.' },
    { term: 'Pagination', definition: 'Dividing a dataset into pages for navigation (previous/next or numbered pages).' },
    { term: 'Parallax', definition: 'A scrolling effect where background layers move at a slower speed than foreground layers, creating depth.' },
    { term: 'Payload', definition: 'The data content of a request or response body — distinct from headers and metadata.' },
    { term: 'PCI DSS', definition: 'Payment Card Industry Data Security Standard — security rules any business handling card data must follow.', aliases: ['pci', 'payment card industry'] },
    { term: 'Performance budget', definition: 'A set of limits on page weight, load time, or Core Web Vitals scores enforced during development to keep a site fast.' },
    { term: 'Playwright', definition: 'A browser automation library from Microsoft used for end-to-end testing across Chromium, Firefox, and WebKit.' },
    { term: 'pnpm', definition: 'A fast, disk-efficient JavaScript package manager that shares packages across projects using hard links.' },
    { term: 'Polyfill', definition: 'Code that implements a modern browser feature in older browsers that don\'t support it natively.' },
    { term: 'Port', definition: 'A numerical endpoint on a server identifying a specific service (e.g., :80 for HTTP, :443 for HTTPS, :3000 for dev servers).' },
    { term: 'PostCSS', definition: 'A tool that transforms CSS using JavaScript plugins — handles autoprefixing, future syntax, and custom transforms.' },
    { term: 'Prettier', definition: 'An opinionated code formatter that automatically enforces consistent style across HTML, CSS, JS, and more.' },
    { term: 'Primary key', definition: 'A column (or set of columns) that uniquely identifies each row in a database table.' },
    { term: 'Progressive enhancement', definition: 'Building a functional baseline experience for all browsers, then adding richer features for more capable ones.' },
    { term: 'Promise', definition: 'A JavaScript object representing the eventual completion (or failure) of an asynchronous operation.' },
    { term: 'Props', definition: 'Inputs passed from a parent component to a child component in React (short for "properties").' },
    { term: 'Protocol', definition: 'A set of agreed-upon rules governing how computers communicate (e.g., HTTP, TCP/IP, WebSocket).' },
    { term: 'Prototype (design)', definition: 'An interactive simulation of a UI used to test and communicate design ideas before writing code.' },
    { term: 'Prototype chain', definition: 'JavaScript\'s inheritance mechanism where objects delegate property lookups up a chain of prototype objects.' },
    { term: 'PWA', definition: 'Progressive Web App — a web app that can feel app-like (offline, installable, push notifications).', aliases: ['progressive web app'] },

    { term: 'Query parameter', definition: 'Key-value pairs appended to a URL after ? (e.g., ?page=2&sort=asc), passed to the server with each request.', aliases: ['query string'] },
    { term: 'Query selector', definition: 'A DOM method (querySelector / querySelectorAll) that finds elements using CSS selector syntax.' },

    { term: 'Race condition', definition: 'A bug where the program\'s outcome depends on the unpredictable order or timing of asynchronous operations.' },
    { term: 'Rate limiting', definition: 'Restricting how many requests a client can make in a time window to protect a service.' },
    { term: 'RBAC', definition: 'Role-Based Access Control — permissions are granted through roles instead of per-user rules.' },
    { term: 'RDBMS', definition: 'Relational Database Management System — a database using tables/relations and SQL (e.g., Postgres).', aliases: ['relational database management system'] },
    { term: 'React', definition: 'A JavaScript library for building component-based user interfaces.' },
    { term: 'Recursion', definition: 'A technique where a function calls itself to solve a problem by breaking it into smaller, identical subproblems.' },
    { term: 'Redux', definition: 'A predictable state container for JavaScript apps using a single store and pure reducer functions.' },
    { term: 'Refactoring', definition: 'Restructuring existing code to improve readability or design without changing its external behavior.' },
    { term: 'Regex', definition: 'Regular expression — a pattern language for matching/searching text.', aliases: ['regular expression'] },
    { term: 'Render blocking', definition: 'Resources (scripts or stylesheets) that must finish loading before the browser can display the page.' },
    { term: 'Responsive design', definition: 'Designing layouts that adapt to different screen sizes and devices.' },
    { term: 'REST', definition: 'A common API style using HTTP verbs and resources (GET/POST/PUT/DELETE).', aliases: ['rest api'] },
    { term: 'Reverse proxy', definition: 'A server that sits in front of backend servers, forwarding requests and hiding internal infrastructure from clients.' },
    { term: 'robots.txt', definition: 'A file that gives search engines rules about which pages they should or shouldn\'t crawl.', aliases: ['robots exclusion protocol'] },
    { term: 'Rollup', definition: 'A JavaScript module bundler optimized for building libraries and packages using ES modules.' },
    { term: 'Router / Routing', definition: 'The system that maps incoming URLs to the appropriate view, handler, or component in an application.' },
    { term: 'RUM', definition: 'Real User Monitoring — performance measurements collected from real visitors in production.' },

    { term: 'SaaS', definition: 'Software as a Service — software delivered via the web as an ongoing subscription.', aliases: ['software as a service'] },
    { term: 'SAML', definition: 'A standard for exchanging authentication/authorization data (common in enterprise SSO).', aliases: ['security assertion markup language'] },
    { term: 'Same-origin policy', definition: 'A browser security model that restricts scripts from reading data from different origins.' },
    { term: 'Sandbox', definition: 'An isolated environment for running code safely, preventing it from affecting external systems.' },
    { term: 'Sans-serif', definition: 'A typeface category without the small decorative strokes (serifs) at the ends of letters — e.g., Arial, Helvetica, Inter.' },
    { term: 'SASS/SCSS', definition: 'CSS preprocessors that add variables, nesting, mixins, and functions to CSS, compiled to standard CSS.', aliases: ['sass', 'scss'] },
    { term: 'Schema (validation)', definition: 'A formal definition of data structure and constraints — used to validate JSON (JSON Schema) or database tables.' },
    { term: 'Scope (JavaScript)', definition: 'The context that determines where a variable is accessible — global, function, or block scope.' },
    { term: 'Scrum', definition: 'An Agile framework using sprints, a backlog, and defined roles/events to deliver work.' },
    { term: 'Scroll snap', definition: 'A CSS feature that snaps the scroll position to defined points, creating controlled carousel-like scrolling.' },
    { term: 'Semantic HTML', definition: 'Using HTML elements by their meaning (<nav>, <main>, <article>, <header>) rather than just for visual appearance.' },
    { term: 'SemVer', definition: 'Semantic Versioning — version numbers like MAJOR.MINOR.PATCH that signal compatibility.', aliases: ['semantic versioning'] },
    { term: 'SEO', definition: 'Search Engine Optimization — improving a site so it ranks higher and earns more qualified traffic.', aliases: ['search engine optimization'] },
    { term: 'SERP', definition: 'Search Engine Results Page — the page of results shown after a search query.' },
    { term: 'Serif', definition: 'A typeface category with small decorative strokes at the ends of letterforms — e.g., Times New Roman, Georgia.' },
    { term: 'Server', definition: 'A computer or program that listens for and processes requests from clients.' },
    { term: 'Serverless', definition: 'A cloud model where you deploy code and the platform handles servers/scaling behind the scenes.' },
    { term: 'Service worker', definition: 'A background script that can cache assets, enable offline, and intercept network requests in PWAs.' },
    { term: 'Session', definition: 'A period of interaction between a user and a web app, tracked server-side and identified by a cookie or token.' },
    { term: 'Session storage', definition: 'Browser storage that lasts only for the current tab/session (per origin).', aliases: ['sessionStorage'] },
    { term: 'Shadow DOM', definition: 'A DOM subtree that encapsulates markup/styles for a web component so it doesn\'t leak globally.' },
    { term: 'Side effect', definition: 'Any observable change a function causes beyond returning a value — network requests, DOM mutations, logging, etc.' },
    { term: 'Single source of truth', definition: 'The principle that each piece of data should live in exactly one place, with everything else referencing it.', aliases: ['ssot'] },
    { term: 'Singleton', definition: 'A design pattern ensuring only one instance of a class exists and is shared across the application.' },
    { term: 'sitemap', definition: 'A file (often XML) that lists a site\'s important URLs to help search engines crawl it.', aliases: ['sitemap.xml'] },
    { term: 'Skeleton loader', definition: 'A placeholder UI that mimics the shape of content while data is loading, reducing perceived wait time.' },
    { term: 'Skeuomorphism', definition: 'A UI style where digital elements mimic real-world objects with textures, shadows, and physical affordances.' },
    { term: 'SLA', definition: 'Service Level Agreement — a contractual uptime/performance commitment.', aliases: ['service level agreement'] },
    { term: 'SLO', definition: 'Service Level Objective — an internal reliability target (often derived from an SLA).', aliases: ['service level objective'] },
    { term: 'Slug', definition: 'A URL-friendly version of a title using lowercase letters, numbers, and hyphens (e.g., my-blog-post).' },
    { term: 'SPA', definition: 'Single-page application — a web app that loads once and updates the UI without full page loads.', aliases: ['single-page application'] },
    { term: 'Specificity', definition: 'The CSS algorithm that determines which rule wins when multiple selectors target the same element.' },
    { term: 'Sprite', definition: 'A single image combining many smaller images (icons), loaded once to reduce HTTP requests.', aliases: ['image sprite', 'css sprite'] },
    { term: 'SQL', definition: 'Structured Query Language — the standard language for querying and manipulating relational databases.', aliases: ['structured query language'] },
    { term: 'SQL injection', definition: 'A vulnerability where attacker input changes a database query (caused by unsafe string concatenation).', aliases: ['sqli'] },
    { term: 'SRI', definition: 'Subresource Integrity — verifies that a fetched script/style matches an expected hash.' },
    { term: 'SSG', definition: 'Static site generation — pages are prebuilt at deploy time into static files.', aliases: ['static site generation'] },
    { term: 'SSL', definition: 'An older name for TLS; people say SSL but modern secure connections use TLS.', aliases: ['secure sockets layer'] },
    { term: 'SSO', definition: 'Single Sign-On — logging in once to gain access to multiple related services or applications.', aliases: ['single sign-on'] },
    { term: 'SSR', definition: 'Server-side rendering — HTML is generated on the server for faster first load/SEO.', aliases: ['server-side rendering'] },
    { term: 'State management', definition: 'The practices and tools (Redux, Zustand, Context) for handling, sharing, and updating application state.' },
    { term: 'Static typing', definition: 'Declaring variable types at compile time so type errors are caught before the code runs (used in TypeScript, Java).' },
    { term: 'Sticky element', definition: 'A CSS-positioned element (position: sticky) that scrolls normally until it hits a threshold, then stays visible.' },
    { term: 'Storybook', definition: 'An open-source tool for developing and documenting UI components in isolation.' },
    { term: 'Stub', definition: 'A minimal fake implementation used in tests to replace a dependency with controlled, predictable behavior.' },
    { term: 'SWC', definition: 'A Rust-based JavaScript/TypeScript compiler designed as a much faster drop-in replacement for Babel.' },

    { term: 'Tailwind CSS', definition: 'A utility-first CSS framework that styles UI using small composable classes.' },
    { term: 'TDD', definition: 'Test-Driven Development — writing failing tests before writing the implementation code that makes them pass.', aliases: ['test-driven development'] },
    { term: 'Technical debt', definition: 'Shortcuts or suboptimal code decisions that create future maintenance burden and slow down development.' },
    { term: 'Template literal', definition: 'A JavaScript string delimited by backticks that supports embedded expressions (${var}) and multiline text.' },
    { term: 'Terminal', definition: 'A text-based interface for entering commands to control the operating system and run programs.', aliases: ['command line', 'shell', 'console'] },
    { term: 'Third-party cookie', definition: 'A cookie set by a domain other than the one being visited — widely used for cross-site ad tracking.' },
    { term: 'Throttle', definition: 'Ensuring a function executes at most once per defined time interval, regardless of how often it\'s triggered.' },
    { term: 'Time to Interactive', definition: 'The point at which a page is fully interactive and reliably responds to user input.', aliases: ['tti'] },
    { term: 'TLS', definition: 'Transport Layer Security — encryption that protects data in transit (e.g., HTTPS).', aliases: ['transport layer security'] },
    { term: 'Tooltip', definition: 'A small informational label that appears when hovering over or focusing on a UI element.' },
    { term: 'Transpiler', definition: 'A compiler that converts source code from one language or syntax version to another (e.g., TypeScript → JavaScript).' },
    { term: 'Tree shaking', definition: 'A bundler optimization that removes unused exports from the final JavaScript bundle to reduce file size.' },
    { term: 'TTFB', definition: 'Time to First Byte — how long until the first byte of the response is received.' },
    { term: 'Turborepo', definition: 'A high-performance build system for JavaScript/TypeScript monorepos, with smart task caching.' },
    { term: 'Type coercion', definition: 'JavaScript\'s automatic conversion of values from one type to another (e.g., "5" + 1 = "51" in JS).' },
    { term: 'TypeScript', definition: 'A typed superset of JavaScript that compiles to JavaScript.', aliases: ['ts'] },

    { term: 'UI', definition: 'User Interface — everything the user sees and directly interacts with in an application.', aliases: ['user interface'] },
    { term: 'Unit testing', definition: 'Testing small pieces of code in isolation to verify they work as expected.' },
    { term: 'Universal rendering', definition: 'Running the same application code on both the server (for initial HTML) and the client (for interactivity).' },
    { term: 'URI', definition: 'Uniform Resource Identifier — a broader identifier concept that includes URLs and URNs.' },
    { term: 'URL', definition: 'Uniform Resource Locator — the full address to a web resource (scheme, host, path, etc.).' },
    { term: 'User agent', definition: 'The browser or client software making an HTTP request, identified to the server via the User-Agent header.' },
    { term: 'User story', definition: 'A short description of a feature from an end user\'s perspective, used to scope development work.' },
    { term: 'UTF-8', definition: 'A Unicode text encoding that supports virtually all written characters and is the web default.' },
    { term: 'UX', definition: 'User Experience — the overall experience a person has using a product, including usability, feel, and accessibility.', aliases: ['user experience'] },

    { term: 'Variable font', definition: 'A font file that stores multiple style variations (weight, width, slant) in a single file, interpolated at render time.' },
    { term: 'Vendor prefix', definition: 'Browser-specific CSS prefixes (-webkit-, -moz-, -ms-) historically used for experimental CSS features.', aliases: ['-webkit-', '-moz-'] },
    { term: 'Version control', definition: 'Tracking changes to files over time so you can recall specific versions — typically done with Git.' },
    { term: 'ViewBox', definition: 'An SVG attribute defining the coordinate system and visible area of the SVG canvas.' },
    { term: 'Viewport', definition: 'The visible area of a page in the browser (especially relevant for responsive layouts).', aliases: ['layout viewport', 'visual viewport'] },
    { term: 'Virtual DOM', definition: 'An in-memory representation of the UI that frameworks (like React) use to compute minimal real DOM updates.' },
    { term: 'Virtual machine', definition: 'Software that emulates a full computer, running its own OS and applications on top of a host system.', aliases: ['vm'] },
    { term: 'Vite', definition: 'A modern frontend build tool/dev server optimized for fast local development using native ES modules.' },
    { term: 'Vitest', definition: 'A Vite-native unit testing framework that shares Vite config and is compatible with the Jest API.' },
    { term: 'Vue', definition: 'A JavaScript framework for building user interfaces with components.', aliases: ['vue.js'] },

    { term: 'WAF', definition: 'Web Application Firewall — filters and monitors HTTP traffic to block common attacks like XSS and SQL injection.', aliases: ['web application firewall'] },
    { term: 'WCAG', definition: 'Web Content Accessibility Guidelines — the main accessibility standard used on the web.', aliases: ['web content accessibility guidelines'] },
    { term: 'Web component', definition: 'A browser-native set of APIs (Custom Elements, Shadow DOM, HTML templates) for creating reusable custom HTML elements.' },
    { term: 'Web crawler', definition: 'A bot that systematically browses the web to index content for a search engine (e.g., Googlebot).' },
    { term: 'Web font', definition: 'A font file (WOFF2, WOFF, TTF) loaded from a server and used to render text in the browser.' },
    { term: 'Web scraping', definition: 'Programmatically extracting data from web pages, typically using an HTTP client and HTML parser.' },
    { term: 'Web standard', definition: 'A specification maintained by W3C or WHATWG that defines how browsers should implement web features.' },
    { term: 'WebAssembly', definition: 'A low-level binary format that runs in the browser at near-native speed (often from Rust/C/C++).', aliases: ['wasm'] },
    { term: 'WebGL', definition: 'A JavaScript API for rendering interactive 2D and 3D graphics in the browser using the GPU.' },
    { term: 'Webhook', definition: 'An HTTP callback that one system sends to another when an event occurs — a way to get real-time notifications.' },
    { term: 'WebP', definition: 'A modern image format that typically achieves smaller files than JPEG/PNG at similar quality.' },
    { term: 'WebRTC', definition: 'Browser technology for real-time peer-to-peer audio/video/data (used for video calls).', aliases: ['webrtc'] },
    { term: 'WebSocket', definition: 'A persistent, two-way connection between browser and server for real-time updates.' },
    { term: 'Webpack', definition: 'A JavaScript bundler that builds and optimizes frontend assets.' },
    { term: 'Widget', definition: 'A small, self-contained UI component (date picker, rating input, etc.) users interact with.' },
    { term: 'Wireframe', definition: 'A low-fidelity sketch of a page layout showing structure and content hierarchy without visual design detail.' },
    { term: 'WOFF/WOFF2', definition: 'Web Open Font Format — compressed font formats optimized for fast delivery in browsers.', aliases: ['woff', 'woff2'] },
    { term: 'WordPress', definition: 'The most widely used open-source CMS, powering a large percentage of websites on the internet.' },
    { term: 'Worker thread', definition: 'A background JavaScript thread (Web Worker) that runs scripts without blocking the main UI thread.' },

    { term: 'XML', definition: 'Extensible Markup Language — a structured text format for data exchange (also used in SVG and RSS).' },
    { term: 'XSS', definition: 'Cross-site scripting — injecting malicious script into a page to run in a user\'s browser.' },

    { term: 'YAML', definition: 'A human-readable data serialization format commonly used for config files (CI/CD pipelines, Docker Compose, etc.).', aliases: ['yaml ain\'t markup language'] },
    { term: 'Yarn', definition: 'A fast JavaScript package manager from Meta, an alternative to npm with workspaces support.' },

    { term: 'Z-index', definition: 'A CSS property controlling the stacking order of positioned elements — higher values appear on top.', aliases: ['z index'] },
    { term: 'Zero-downtime deployment', definition: 'A release strategy ensuring the service stays available to users throughout the deploy process.' },
    { term: 'Zustand', definition: 'A small, fast state management library for React using a simple hook-based API.' },

  ];

  function sortKey(s){
    return String(s||'')
      .toLowerCase()
      .replace(/[""]/g,'"')
      .replace(/[']/g,"'")
      .replace(/[^a-z0-9]+/g,' ')
      .trim();
  }

  entries.sort((a,b)=>{
    const ak=sortKey(a?.term);
    const bk=sortKey(b?.term);
    if(ak<bk) return -1;
    if(ak>bk) return 1;
    return String(a?.term||'').localeCompare(String(b?.term||''));
  });

  window.GLOSSARY_ENTRIES = entries;
})();